### ISSUE TITLE
Command with a trigger of 'poll' failed

### ISSUE THREAD

**Issue by gblue1223** [M-Mueller/mattermost-poll#18]
I've installed Poll according to the [document](https://github.com/M-Mueller/mattermost-poll). But I couldn't run the command. No matter what configuration, it keeps saying `Command with a trigger of 'poll' failed`. I've tested both [localhost](https://github.com/M-Mueller/mattermost-poll#setup) way and [docker](https://github.com/M-Mueller/mattermost-poll#docker) way but, no luck.

However, Poll server seems working well because it returns "Poll server is running" when I execute "curl http://localhost:5002". Also, in the MatterMost container, command `ping poll` respond well, too. Any ideas about this trouble?

#### docker-compose.yml
```bash
  web:
    build: web
    ports:
      - "8866:80"
      - "8867:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true

poll:
    build:
      context: poll
      args:
	- mattermost_url="http://web:8866"
        - mattermost_tokens=['qnz93keghpycp8ckx3wspw34eo']
        - mattermost_pa_token="<personal-access-token>"
    ports:
      - "5002:5000"
    restart: unless-stopped
    volumes:
      - ./volumes/poll:/app/volume:rw
``` 

#### config.json
```bash
...
"AllowedUntrustedInternalConnections": "poll" # "localhost"
...
```

#### The slash commands configuration on MatterMost
```bash
Request URL: http://poll:5002 # Port 5000 is already in use so I changed it
Request Method: POST
```

**Comment by gblue1223** [comment]
I've made a progress. `System Console/Logs` was saying like below:
```json
{"level":"error","ts":1533880031.2649605,"caller":"web/handlers.go:142","msg":"Command with a trigger of 'poll' failed","path":"/api/v4/commands/execute","request_id":"fx9nmyq49bgs3emwa76sfksmke","ip_addr":"172.16.2.144","user_id":"f6k8gg6bx78ifdxka3z3mgnrxr","method":"POST","err_where":"command","http_code":500,"err_details":"Post http://poll:5002: dial tcp 172.18.0.4:5002: connect: connection refused"}
```

So, I've change the slash commands configuration like this:
```bash
...
"AllowedUntrustedInternalConnections": "poll" # 172.18.0.0/8 localhost
...
```
```bash
Request URL: http://poll:5000 # Despite the exposed port is 5002, MM container failed to connect to port 5002 but port 5000.
Request Method: POST
````
Afterwards, the error message came from MM has changed like this `The integration is not correctly set up: Invalid token.` but there is no logs  for this on either `System Console/Logs` or `docker-compose's log`.

**Comment by M-Mueller** [comment]
Maybe try to set the port to 5002 in the settings.py as well. Mapping the port in docker sometimes has weird effects.
For the `The integration is not correctly set up: Invalid token.` error, check that the mattermost_tokens has the same value as in MM (should look like this: `- mattermost_tokens=["9pcdpmtzwt8bidtapiw11fcg1h"]`)

**Comment by gblue1223** [comment]
Thanks for the reply @M-Mueller. I've built the compose again with `docker-compose build` command. And it works now!
Here are my configurations for people who is struggling with.

#### docker-compose.yml
```yml
version: "2"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "8866:80"
      - "8867:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true

  poll:
    build:
      context: poll
      args:
        - mattermost_url="http://web"
        - mattermost_tokens=['qnz93keghpycp8ckx3wspw34eo']
        - mattermost_pa_token="<personal-access-token>"
    ports:
      - "5002:5000"
    restart: unless-stopped
    volumes:
      - ./volumes/poll:/app/volume:rw
```

#### poll/settings.py
```bash
"""This file contains all user settings of the application"""


# Path to the database file.
DATABASE = 'volume/poll.db'

# Address to listen on
WEBSERVER_ADDRESS = '0.0.0.0'

# Port of the webserver
WEBSERVER_PORT = 5000

# Optional list of Mattermost tokens (list of strings e.g. ['abc123', 'xyz321'])
MATTERMOST_TOKENS = ['qnz93keghpycp8ckx3wspw34eo']

# URL of the Mattermost server
MATTERMOST_URL = "http://web"

# Private access token of some user.
# Required to resolve username in 'public' polls.
# https://docs.mattermost.com/developer/personal-access-tokens.html
MATTERMOST_PA_TOKEN = "<personal-access-token>"

# Uncomment the following lines to enable file logging:
#import logging
#logging.basicConfig(filename='poll.log', level=logging.DEBUG)

import logging
logging.basicConfig(filename='volume/poll.log', level=logging.INFO)
```

#### Mattermost: Slash Commands
```bash
Request URL: http://poll:5000
Request Method: POST
```

```bash
Token: qnz93keghpycp8ckx3wspw34eo
```

#### Mattermost: System Console -> Advanced -> Developer
```bash
Allow untrusted internal connections to: poll
```
